config/routes.rb
Rails.application.routes.draw do
  # NOTE: Awesome clean routes, might suggest closing off some routes for views that may not be used
  resources :sales
  resources :items, path: "inventory"
  devise_for :users
  resources :businesses
  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:
  # get("/your_first_screen", { :controller => "pages", :action => "first" })

  root "home#index"

  get "/rake_tasks", { :controller => "rake_tasks", :action => "show" }
  get "/run_task", { :controller => "rake_tasks", :action => "run_task" }
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  before_action :set_business, only: %i[ show edit update destroy ]

  # Commented out cause don't need it for MVP Features but will be used in Future Features
  # GET /businesses or /businesses.json
  def index
      redirect_to root_path, alert: "You cannot access businesses at this time."
    @businesses = current_user.businesses
  end

  # GET /businesses/1 or /businesses/1.json
  def show
  end

  # GET /businesses/new
  def new
    @business = Business.new
  end

  # GET /businesses/1/edit
  def edit
  end

  # POST /businesses or /businesses.json
  def create
    @business = Business.new(business_params)
    @business.owner = current_user  # always set owner to current user

    respond_to do |format|
      if @business.save
        format.html { redirect_to @business, notice: "Business was successfully created." }
        format.json { render :show, status: :created, location: @business }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /businesses/1 or /businesses/1.json
  def update
    respond_to do |format|
      if @business.update(business_params)
        format.html { redirect_to @business, notice: "Business was successfully updated." }
        format.json { render :show, status: :ok, location: @business }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @business.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /businesses/1 or /businesses/1.json
  def destroy
    @business.destroy!

    respond_to do |format|
      format.html { redirect_to businesses_path, status: :see_other, notice: "Business was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_business
    @business = Business.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def business_params
    params.expect(business: [ :name ])
  end
end

app/views/businesses/_business.html.erb
<div id="<%= dom_id business %>" class="card mb-3">
  <div class="card-header">
    <h5 class="mb-0"><%= business.name %></h5>
  </div>

  <div class="card-body">
    <p class="card-text">
      <strong>Owner:</strong>
      <%= business.owner&.name || "Unknown" %>
    </p>

    <p class="card-text">
      <strong>Type of Products:</strong>
      <%= business.items_count %>
    </p>
  </div>
</div>

app/views/businesses/_form.html.erb
<%= form_with(model: business, class: "needs-validation") do |form| %>
  <% if business.errors.any? %>
    <div class="alert alert-danger">
      <h4 class="alert-heading"><%= pluralize(business.errors.count, "error") %> prohibited this business from being saved:</h4>
      <ul class="mb-0">
        <% business.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control", required: true %>
  </div>

  <%= form.submit "Save", class: "btn btn-primary w-100" %>
<% end %>

app/views/businesses/edit.html.erb
<% content_for :title, "Editing Business" %>

<div class="row">
  <div class="offset-md-3 col-md-6">
    <div class="card mb-3">
      <h5 class="card-header">Editing Business</h5>

      <div class="card-body">
        <%= render "form", business: @business %>

        <hr>

        <div class="d-flex justify-content-between">
          <%= link_to "Show this business", @business, class: "btn btn-outline-secondary w-100" %>
          <%# NOTE: Love the note for your future self %>
          <%# Will be using this in the future but not needed for Core Features %>
          <%#= link_to "Back to businesses", businesses_path, class: "btn btn-outline-secondary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/businesses/index.html.erb
<% content_for :title, "Businesses" %>

<div class="d-flex justify-content-between align-items-center mb-4">
  <h1 class="mb-0">My Businesses</h1>
  <%= link_to "New Business", new_business_path, class: "btn btn-success" %>
</div>
<hr>
<div id="businesses" class="row g-4">
  <% @businesses.each do |business| %>
    <div class="col-md-4">
      <%= render business %>
      <%= link_to "Show this business", business, class: "btn btn-primary w-100" %>
    </div>
  <% end %>
</div>

app/views/businesses/new.html.erb
<% content_for :title, "New Business" %>

<div class="row">
  <div class="offset-md-3 col-md-6">
    <div class="card mb-3">
      <h5 class="card-header">New Business</h5>

      <div class="card-body">
        <%= render "form", business: @business %>

        <%# Will be using this in the future but not needed for Core Features %>
        <!--        <hr>
        
        <div class="d-flex justify-content-between">
          <%#= link_to "Back to businesses", businesses_path, class: "btn btn-outline-secondary w-100" %>-->
        <!--        </div>-->

      </div>
    </div>
  </div>
</div>

app/views/businesses/show.html.erb
<div class="row">
  <div class="offset-md-3 col-md-6">
    <%= render @business %>

    <div class="mt-3 d-flex gap-2">
      <%= link_to "Edit this business", edit_business_path(@business), class: "btn btn-outline-primary" %>
      <%# Will be using this in the future but not needed for Core Features %>
      <%#= link_to "Back to businesses", businesses_path, class: "btn btn-outline-secondary" %>
      <%= button_to "Destroy this business", @business, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
    </div>
  </div>
</div>