config/routes.rb
Rails.application.routes.draw do
  # NOTE: Awesome clean routes, might suggest closing off some routes for views that may not be used
  resources :sales
  resources :items, path: "inventory"
  devise_for :users
  resources :businesses
  # This is a blank app! Pick your first screen, build out the RCAV, and go from there. E.g.:
  # get("/your_first_screen", { :controller => "pages", :action => "first" })

  root "home#index"

  get "/rake_tasks", { :controller => "rake_tasks", :action => "show" }
  get "/run_task", { :controller => "rake_tasks", :action => "run_task" }
end

app/views/shared/_cdn_assets.html.erb
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />

app/views/shared/_flash.html.erb
<div class="alert alert-<%= css_class %> alert-dismissible fade show" role="alert">
  <%= message %>

  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <div class="container">
    <%= link_to "SimpleShop", root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to items_path, class: "nav-link" do %>
              <i class="fas fa-boxes-stacked fa-fw"></i>

            Inventory
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to sales_path, class: "nav-link" do %>
            <i class="fas fa-receipt fa-fw"></i>

            Sales
          <% end %>
        </li>
        <li class="nav-item">
          <% if current_user.businesses.any? %>
            <%= link_to business_path(current_user.businesses.first), class: "nav-link" do %>
              <i class="fas fa-store fa-fw"></i>
              <%= current_user.businesses.first.name %>
            <% end %>
          <% else %>
            <%= link_to new_business_path, class: "nav-link" do %>
              <i class="fas fa-plus fa-fw"></i>
              Create Business
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>

    <ul class="navbar-nav ms-auto">
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= current_user.name %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div> <%# NOTE: Seems to extra end </div> %>
</nav>